config/routes.rb
Rails.application.routes.draw do
  # Correct this. Make things actually use controllers
  root to: 'sessions#new'
  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"
  resources :blogs do
    resources :posts, except: [:index] do
    end
  end
  resources :posts, only: [:index]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resource :dashboard, only: [:show]
  resource :text_post, only: [:new]
  resource :photo_post, only: [:new]
  resource :quote_post, only: [:new]
  resource :link_post, only: [:new]
  resource :chat_post, only: [:new]
  resource :audio_post, only: [:new]
  resource :video_post, only: [:new]
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :title, presence: true
	validates :owner_id, presence: true, on: :create
	has_many(
		:posts,
		dependent: :destroy
	)
	belongs_to(
		:owner,
		class_name: 'User',
		foreign_key: :owner_id
	)
	
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :post_type, presence: true
  belongs_to :blog


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  before_validation :ensure_session_token
  validates :email, :password_digest, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true, on: [:create]

  validates :password, length: {minimum: 4, allow_blank: true}

  has_many(
    :blogs,
    foreign_key: :owner_id
  )
  has_many(
    :posts,
    through: :blogs,
    source: :posts
  )

  def primary_blog
    self.blogs.each do |blog|
      return blog if blog.primary
    end
  end

  def selected_blog
    @selected_blog ||= self.primary_blog
  end

  def selected_blog=(blog)
    @selected_blog = blog
  end

  def generate_token
    SecureRandom::urlsafe_base64(32)
  end

  def self.find_by_credentials(username, pt_password)
    user = User.find_by_username(username)
    return nil unless user.try(:is_password?, pt_password)
    user
  end

  def reset_session_token!
    self.session_token = generate_token
    self.save!
    self.session_token
  end

  def password=(pt_password)
    @password = pt_password
    self.password_digest = BCrypt::Password.create(pt_password)
  end

  def is_password?(pt_password)
    BCrypt::Password.new(self.password_digest) == pt_password
  end

  private

  def ensure_session_token
    self.session_token ||= generate_token
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :check_logged_in
	before_action only: :edit 

	def index
		@blogs = current_user.blogs
		render :index
	end

	def show
		@blog = Blog.find(params[:id])
		@posts = @blog.posts
		render :show
	end

	def new
		@blog = Blog.new
		render :new
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.owner_id = current_user.id

		if @blog.save
			redirect_to blog_url(@blog)
		else
			flash.now[:error] = @blog.errors.full_messages
			render :new
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		if @blog.owner == current_user
			@blog.destroy
			redirect_to blogs_url
		else
			flash[:error] = 'Only the owner may delete this blog'
			redirect_to blogs_url
		end
		
	end

	def edit
		@blog = Blog.find(params[:id])
		render :edit
	end

	def update
		@blog = Blog.find(params[:id])
		@blog.update_attributes(blog_params)

		if @blog.save
			redirect_to blog_url(@blog)
		else
			flash.now[:error] = @blog.errors.full_messages
			render :edit
		end

	end

	private

	def blog_params
		params.require(:blog).permit(:title, :url, :description, :avatar_url, :primay)
	end



end

app/controllers/chat_posts_controller.rb
class ChatPostsController < ApplicationController
  before_action :check_log_in
	layout 'blank'
	def new
		@blogId = current_user.selected_blog.id
		render :new
	end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :check_log_in
  def show
    @markdown = get_markdown_renderer
    render 'dashboards/dashboard'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_log_in

	def index
		@posts = current_user.posts
		render :index
	end

	def show
		@post = Post.find(params[:id])
		if @post
			render :show
		else
			flash[:error] = 'Post could not be found'
			redirect_to dashboard_url
		end
	end

	def new
		@post = Post.new
		render :new
	end

	def create
    @markdown = get_markdown_renderer
		@post = Post.new(post_params)
    @post.caption = parse_chat(post_params[:caption]) unless post_params[:caption].nil?
		if @post.save
      render :show, layout: 'layouts/blank'
		else
			flash.now[:error] = @post.errors.full_messages
			render 'dashboards/dashboard'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.owner == current_user
			@post.destroy
			redirect_to posts_url
		else
			flash[:error] = 'Only the owner may delete this blog'
			redirect_to posts_url
		end

	end

	def edit
		@post = Post.find(params[:id])
		render :edit
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)

		if @post.save
			redirect_to post_url(@post)
		else
			flash.now[:error] = @post.errors.full_messages
			render :edit
		end

	end

	private

	def post_params
		params.require(:post).permit(:title, :media_url, :description, :post_type, :blog_id, :url, :caption)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'splash', only: [:new, :create]
  before_action :ensure_logged_out, only: [:new, :create]
  def new

  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to dashboard_url
    else
      render :new
      #render error
    end
  end

  def destroy
    logout
    redirect_to root_url
    # redirect user to new session
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_out, only: [:new, :create]
  layout 'splash', only: [:new, :create]
  def new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      @blog = @user.blogs.create(title: "Default blog", primary: true, avatar_url: "https://s3-us-west-1.amazonaws.com/headsuplolimages/thumbnail_#{(1..10).to_a.sample}.png")
      login!(@user)
      redirect_to dashboard_url #render dashboard with first blog showing
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
      redirect_to root_url #render dashboard with first blog
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    @current_user = user
    user.selected_blog
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def check_log_in
    redirect_to root_url unless logged_in?
  end

  def get_embed_link(passed_url)
    obj = $embedly_api.oembed(url: passed_url, maxwidth: 500)
  end

  def get_markdown_renderer
    $markdown
  end

  def parse_chat(text)
    parsed_chat = []
    lines = text.split("\r\n")
    lines.each do |line|
      lineFragments = line.split(':')
      lineFragments[0] = "**" + lineFragments.first + "**" unless lineFragments[1].nil?

      if lineFragments[0].nil?
        parsed_chat << "\r\n"
      else
        parsed_chat << lineFragments.join(":")
      end
    end
    parsed_chat.join("\r\n")

  end

  def ensure_logged_out
    redirect_to dashboard_url if logged_in?
  end

  def get_splash_image
    "https://s3-us-west-1.amazonaws.com/headsuplolimages/splash#{("1".."10").to_a.sample}.jpg"
  end

  def get_background_image(thumbnail_url)
    num = thumbnail_url[-5]
    num = "10" if num == "0"
    test = "https://s3-us-west-1.amazonaws.com/headsuplolimages/background_#{num}_#{(1..2).to_a.sample}.jpg"
    test
  end

end

app/helpers/audio_posts_helper.rb
module AudioPostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/chat_posts_helper.rb
module ChatPostsHelper
end

app/helpers/link_posts_helper.rb
module LinkPostsHelper
end

app/helpers/photo_posts_helper.rb
module PhotoPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quote_posts_helper.rb
module QuotePostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_posts_helper.rb
module VideoPostsHelper
end

app/views/dashboard/_main_navbar.html.erb
  <div class='mainHeader'>
    <div class='headerIcon'>
    </div>
    <div class='headerNavigationWrapper'>
      <div class='headerMainNavbar'>
        <% if current_user %>
          <a href='#'>Home</a>
          <a href='#'>Settings</a>
          <%= button_to "Log Out", session_url, {method: :delete} %>
        <% else %>
        <% end %>
      </div>
    </div>


  </div>

app/views/dashboards/_error_404.html.erb
<img src='https://s3-us-west-1.amazonaws.com/headsuplolimages/404error.bmp'>
<img>

app/views/dashboards/_main_navbar.html.erb
  <div class='mainHeader'>
    <div class='headerIcon'>
    </div>
    <div class='headerNavigationWrapper'>
      <div class='headerMainNavbar'>
        <% if current_user %>

          <div class='mainNavbarButtonWrapper'>
            <a href='/dashboard'>
              <span class='homeIcon glyphicon glyphicon-home'></span>
            </a>
          </div>

          <div class='mainNavbarButtonWrapper'>
            <a href='#'>
              <span class='optionsIcon glyphicon glyphicon-cog'></span>
            </a>
          </div>

          <div class='mainNavbarButtonWrapper'>
            <%= button_to "", session_url, {method: :delete, class: 'logoutButton glyphicon glyphicon-off'} %>
            <span class='logoutIcon glyphicon glyphicon-off'><span>
          </div>

        <% else %>
        <% end %>
      </div>
    </div>


  </div>

app/views/dashboards/_modal_post.html.erb
<%= javascript_tag do %>
  window.blogURL = "<%=j users_url %>";
<% end %>

<form id='newPostForm' >
	
</form>

app/views/dashboards/_post.html.erb
  <% if(post.post_type == 'Text') %>

    <%= render partial: 'text_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% elsif(post.post_type == 'Photo') %>

    <%= render partial: 'photo_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% elsif(post.post_type == 'Quote') %>

    <%= render partial: 'quote_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% elsif(post.post_type == 'Link') %>

    <%= render partial: 'link_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% elsif(post.post_type == 'Chat') %>

    <%= render partial: 'chat_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% elsif(post.post_type == 'Audio') %>

    <%= render partial: 'audio_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% elsif post.post_type == 'Video' %>

    <%= render partial: 'video_posts/show', layout: 'layouts/blank', locals: { post: post } %>

  <% end %>

app/views/dashboards/_post_selector.html.erb
    <div class='dashboardNavBarButtonWrapper' >
      <nav class='row'>
        <div class='dashboardNavbarButtons'>
          <div class='newPostButtonWrapper col-xs-1'>
            <a class='newPostButton' id='newPostText' href='#'>
              <i class="glyphicon glyphicon-font" path='Text'></i>
              <span class='newPostLabel' id='textPostLabel' path='Text'>Text</span>
            </a>
          </div>

          <div class='newPostButtonWrapper col-xs-1'>
            <a class='newPostButton' id='newPostPhoto' href='#'>
              <i class="glyphicon glyphicon-camera" path='Photo'></i>
              <span class='newPostLabel' id='photoPostLabel' path='Photo'>Photo</span>
            </a>
          </div>

          <div class='newPostButtonWrapper col-xs-1'>
            <a class='newPostButton' id='newPostQuote' href='#'>
              <i class="glyphicon glyphicon-quote" path='Quote'>&#8220</i>
              <span class='newPostLabel' id='quotePostLabel' path='Quote'>Quote</span>
            </a>
          </div>

          <div class='newPostButtonWrapper col-xs-1'>
            <a class='newPostButton' id='newPostLink' href='#'>
              <i class='glyphicon glyphicon-link newPostLabel' path='Link'></i>
              <span class='newPostLabel' id='linkPostLabel' path='Link'>Link</span>
            </a>
          </div>

          <div class='newPostButtonWrapper col-xs-1'>
              <a class='newPostButton' id='newPostChat' href='#'>
                <i class="glyphicon glyphicon-comment" path='Chat'></i>
                <span class='newPostLabel' id='chatPostLabel' path='Chat'>Chat</span>
              </a>
          </div>

          <div class='newPostButtonWrapper col-xs-1'>
            <a class='newPostButton' id='newPostAudio' href='#'>
              <i class="glyphicon glyphicon-headphones" path='Audio'></i>
              <span class='newPostLabel' id='audioPostLabel' path='Audio'>Audio</span>
            </a>
          </div>

          <div class='newPostButtonWrapper col-xs-1'>
            <a class='newPostButton' id='newPostVideo' href='#'>
              <i class="glyphicon glyphicon-facetime-video" path='Video'></i>
              <span class='newPostLabel' id='videoPostLabel' path='Video'>Video</span>
            </a>
          </div>
        </div>

      </nav>
    </div>
  </div>

app/views/dashboards/_right_navbar.html.erb
<div class='blogControlsPanel panel'>
  <ul class='blogControls'>
    <div class='blogSelectorWrapper dropdown'>
      <button class='btn dropdown-toggle sr-only' type='button' data-toggle='dropdown'>
        <%= current_user.selected_blog.title %>
        <span class='caret'></span>
      </button>
      <button class='blogSelectorButton btn dropdown-toggle' type='button' data-toggle='dropdown'>
        <%= current_user.selected_blog.title %>
        <span class='caret'></span>
      </button>
      <ul class='blogDropDownSelector dropdown-menu' role='menu' href='#'>
        <% blogs.each do |blog| %>
          <li class='blogSelectionListItem' role='presentation'>
            <a class='blogSelectionText' role='menuitem' tabindex='-1' href='#'>
              <%= blog.title %>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
    <li class='blogPostsControl'>
      <a href='#' class='blogPostsLink'>
        Posts
      </a>
    </li>
    <li class='followersListItem'>
      <a href='#' class='followersLink'>Followers</a>
    </li>
    <li class='activityListItem'>
      <a href='#' class='activityLink'>Activity</a>
    </li>
  </ul>

app/views/dashboards/dashboard.html.erb
<div class='dashboardContent container'>
  <div class='dashboardMainView row'>
    <div class='panel col-xs-9'>
      <div class='postsWrapper'>
        <div class='modalWrapper'>

          <div class='dashboardPostsNavbar'>
            <%= render partial: "dashboards/post_selector" %>
          </div>

          <%= render partial: 'dashboards/modal_post', layout: 'layouts/post_modal' %>
        </div>
        <% unless current_user.selected_blog.nil? %>
          <% current_user.selected_blog.posts.sort_by{|post| post[:created_at]}.reverse.each do |post| %>

              <%= render partial: 'dashboards/post',
                layout: 'layouts/post',
                locals: { post: post, markdown: @markdown } %>

          <% end %>
        <% end %>
      </div>
      </div>
      <div class='dashboardRightNavbar col-xs-3'>
        <%= render partial: 'dashboards/right_navbar', layout: 'layouts/blank', locals: { blogs: current_user.blogs} %>
      </div>
    </div>



  </div>
</div>
  <%= javascript_tag do %>
  	window.selectedBlogId = '<%=j current_user.selected_blog.id.to_s %>';
    window.selectedBackground = '<%=j get_background_image(current_user.selected_blog.avatar_url) %>'
  <% end %>